# main text of home
name: Aly Raffauf
shortname: Aly Raffauf
bio: Digital Marketer in Atlanta, Ga.

# twitter summary info
description: Digital Marketer in Atlanta, Ga.

picture: assets/images/aly_circlepfp.jpeg

url: https://aly.raffauflabs.com
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
#facebook: myfacebook
# twitter: alychace
github: alyraffauf
email: aly@raffauflabs.com
linkedin: http://linkedin.com/in/alyraffauf/

plugins:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]

