# main text of home
name: Alexandra Chace
shortname: Aly Chace
bio: PhD student in Atlanta, Ga.

# twitter summary info
description: PhD student in Atlanta, Ga.

picture: assets/images/alymarch222021.jpeg

url: https://alychace.com
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: alychace
github: leximch
email: me@alychace.com

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
